services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: temporaltrace-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1' -No"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  api:
    build:
      context: ./backend/TemporalTrace.Api
      dockerfile: Dockerfile
    container_name: temporaltrace-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=TemporalTraceDb;User Id=sa;Password=Your_password123;Encrypt=True;TrustServerCertificate=True"
    ports:
      - "5294:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/temporal-trace-ui
      dockerfile: Dockerfile
    container_name: temporaltrace-frontend
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  sql_data:
